---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: install apache
      package: 
        name: httpd
        state: latest
      tags: install
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
      tags: config
    - name: create index.html
      file:
        path: /var/www/html/index.html
        state: touch
      tags: config, configuracion # se puede poner más de un tag
    - name: add a line to index.html
      copy:
        content: "Hello World!"
        dest: /var/www/html/index.html
      tags: config
    - name: uninstall apache
      package: 
        name: httpd
        state: absentlatest
      tags: never, uninstall  #para ejecutareste tag hay que ponerlo expresamente en la línea de comandos