---
- hosts: "{{ hosts }}"
  become: true
  tasks:
 #   - name: copio fichero de aws al server (remote_src=no) 
 #     copy:
 #       src: /var/tmp/file1.txt
 #       dest: /tmp/file1.txt
 #       owner: yverasae
 #       group: yverasae
 #       mode: '0644'
 #       remote_src: no   # si queremos copiar al reves, del server cliente al awx, se tiene que poner yes
    - name: creamos nuestro template
      template:
        src: "/var/tmp/linux_file.conf.j2"
        dest: "/var/tmp/file.conf"
        owner: root
        group: root
        mode: '0644'  