---
- hosts: "{{ hosts }}"
  become: true
  tasks:
  - name: "creamos lv {{ lvname }} en vg {{ vgname }}"
    lvol:
      vg: "{{ vgname }}" 
      lv: "{{ lvname }}"
      size: "{{ size }}"
  - name: Create fs test1
    filesystem:
      fstype: "{{ fstype }}"
      dev: "/dev/{{ vgname }}/{{ lvname }}"
  - name: "montamos el fs {{ fsname }}"
    mount:
      path: "{{ fsname }}"
      src: "/dev/{{ vgname }}/{{ lvname }}"
      fstype: "{{ fstype }}"
      state: mounted